# Generated by Django 3.2 on 2021-09-10 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='static/uploads')),
                ('image', models.ImageField(upload_to='static/banner')),
                ('category', models.CharField(max_length=10)),
                ('productionyear', models.DateField()),
                ('movietrailer', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(7)])),
                ('firstsignedin', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
