# Generated by Django 3.2 on 2021-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieupload',
            name='movietrailer',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movieupload',
            name='productionyear',
            field=models.CharField(max_length=30),
        ),
    ]
